src/Entity/Payment.php
<?php
declare(strict_types=1);
/**
 * Created by PhpStorm.
 * User: richard
 * Date: 23.12.17
 * Time: 14:01
 */

namespace App\Entity;


class Payment
{
    public const STATE_PAID = 1;
    public const STATE_WAITING = 0;
    public const STATE_PROCESSING = 2;

    /**
     * @var \DateTime
     */
    private $createdAt;
    /**
     * @var int
     */
    private $state;
    /**
     * @var \DateTime|null
     */
    private $payedAt;
    /**
     * @var int
     */
    private $amount;
    /**
     * @var string
     */
    private $currency;


    public function getQrCodeMessage(): string
    {
        return "lightning:lntb91u1pdrukf6pp5l5hsg52tnlxc60w8pha2szp3ypuadls2hpw8ysmclr6a3gctnw6sdzvxgsy2umswfjhxum0yppk76twypgxzmnwvykzqveq2d3kzmrpyppks6tsypr8yctswp6kxcmfdehsnhrr7s5724rr0rsv2vgfeprrtp69g7algnd27972xts9ee4duz7xaq42t568mgnmadwgqtmy6n98rr9vm6trxaw4r7yf0um98nqepjgp47675k";
    }

    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    public function getState(): int
    {
        return $this->state;
    }

    public function getNiceState(): string
    {
        switch ($this->state) {
            case self::STATE_PAID: return "Paid";
            case self::STATE_PROCESSING: return "Processing";
            case self::STATE_WAITING: return "Waiting";
            default: throw new \DomainException("Unkown state!");
        }
    }

    public function getPayedAt(): ?\DateTime
    {
        return $this->payedAt;
    }

    public function getAmount(): int
    {
        return $this->amount;
    }

    public function getNiceAmount(): string
    {
        return sprintf("%.2f", $this->amount / 100);
    }

    public function getCurrency(): string
    {
        return $this->currency;
    }

    public function __construct(int $state, int $amount, string $currency)
    {
        $this->createdAt = new \DateTime();
        $this->state = $state;
        $this->amount = $amount;
        $this->currency = $currency;
    }
}

src/Controller/DashboardController.php
<?php declare(strict_types=1);
/**
 * Created by PhpStorm.
 * User: richard
 * Date: 23.12.17
 * Time: 12:52
 */

namespace App\Controller;

use App\Entity\Cashier;
use App\Form\Config\NewInvoiceType;
use App\Repository\ConfigRepository;
use App\Service\Twig\SatoshiConverter;
use Doctrine\ORM\EntityManagerInterface;
use Endroid\QrCode\QrCode;
use LightningSale\LndClient\Client as LndRestClient;
use LightningSale\LndClient\Model\Invoice;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * Class DashboardController
 * @package App\Controller\Cashier
 * @Route("/dashboard", name="cashier_dashboard_")
 * @Security("is_granted('ROLE_CASHIER')")
 */
class DashboardController extends Controller
{
    private $lndClient;
    private $em;

    public function __construct(LndRestClient $lndClient, EntityManagerInterface $em)
    {
        $this->lndClient = $lndClient;
        $this->em = $em;
    }


    /**
     * @Route("/", name="index")
     */
    public function indexAction(): Response
    {
        $form = $this->createForm(NewInvoiceType::class,null, [
            'action' => $this->generateUrl("cashier_dashboard_new_invoice")
        ]);

        $invoices = $this->lndClient->listInvoices(true);
        $invoices = array_filter($invoices, function(Invoice $invoice) {
            return new \DateTime("-1 days") < $invoice->getExpiry();
        });
        usort($invoices, function (Invoice $a, Invoice $b) {
            return $b->getCreationDate() <=> $a->getCreationDate();
        });

        return $this->render("Dashboard/dashboard.html.twig", [
            'invoices' => $invoices,
            'form' => $form->createView(),
            'now' => new \DateTime(),
        ]);
    }

    /**
     * @Route("/new_invoice", name="new_invoice")
     * @param Cashier $user
     */
    public function createInvoiceAction(Request $request, UserInterface $user, SatoshiConverter $convertSatoshi, ConfigRepository $configRepository): Response
    {
        $form = $this->createForm(NewInvoiceType::class);
        $form->handleRequest($request);
        $data=$form->getData();

        $localAmount = (float) $data['amount'];
        $amount = (string) $convertSatoshi->localToSatoshi($localAmount); // Extremely buggy ?!
        $timeoutConfig = $configRepository->getConfig(ConfigRepository::INVOICE_TIMEOUT);
        $formatSatoshi = $convertSatoshi->formatSatoshi($amount);

        $user->createInvoice(
            $this->lndClient,
            $amount,
            sprintf("LightningSale %s", $formatSatoshi),
            (int) $timeoutConfig->getValue()
        );

        $this->em->flush();

        return $this->redirectToRoute("cashier_dashboard_index");
    }

    /**
     * @Route("/explorer/{txId}", name="explorer")
     */
    public function transactionAction(string $txId, LndRestClient $lndClient): Response
    {
        $testnet = $lndClient->getInfo()->isTestnet();
        if ($testnet)
            return new RedirectResponse(sprintf("https://www.blocktrail.com/tBTC/tx/%s", $txId));

        return new RedirectResponse(sprintf("https://www.blocktrail.com/BTC/tx/%s", $txId));
    }

    /**
     * @Route("/qrcode/{message}", requirements={"message": ".+"})
     */
    public function createQrCodeAction(string $message): Response
    {
        $qrCode = new QrCode($message);
        $qrCode->setSize(1000);

        return new Response($qrCode->writeString(),200, ['Content-Type' => $qrCode->getContentType()]);
    }
}

src/Controller/Merchant/DashboardController.php
<?php
/**
 * Created by PhpStorm.
 * User: richard
 * Date: 23.12.17
 * Time: 12:52
 */

namespace App\Controller\Merchant;
use App\Entity\Payment;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class DashboardController
 * @package App\Controller\Merchant
 * @Route("/dashboard", name="cashier_dashboard_")
 * @Security("is_granted('ROLE_CASHIER')")
 */
class DashboardController extends Controller
{
    /**
     * @Route("/", name="index")
     */
    public function indexAction(): Response
    {
        /** @var Payment[] $invoices */
        $invoices = [];
        foreach (range(0,100) as $index)
            $invoices[] = new Payment(Payment::STATE_PAID, random_int(100,1000)* 10,"NOK");

        return $this->render("Merchant/Dashboard/index.html.twig", ['invoices' => $invoices]);
    }
}

templates/Merchant/Dashboard/index.html.twig
{% extends 'base.html.twig' %}

{% block headerLeft %}
    <li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-sign-out"></i> Sign out</a></li>
{% endblock %}

{% block headerRight %}
    <li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-user"></i> Profile</a></li>
    <li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-cog"></i> Settings</a></li>
{% endblock %}

{% block body %}
    <div class="container ">
        <div class="row justify-content-center align-items-center">
            <div class="col-8">
                <form class="form form-horizontal">
                    <div class="form-group row">
                        <label for="inputEmail3" class="col-sm-2 col-form-label col-form-label-lg">Description</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control form-control-lg" placeholder="">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputEmail3" class="col-sm-2 col-form-label col-form-label-lg">Charge</label>
                        <div class="col-sm-9">
                            <input type="number" class="form-control form-control-lg" placeholder="15 $">
                        </div>
                        <div class="col-sm-1">
                            <button type="submit" class="btn btn-default btn-lg">Create</button>
                        </div>
                    </div>

                    <div class="row justify-content-md-center">
                        <div class="col-sm-8">
                            <div class="row">
                                <div class="col">
                                    <button type="button" class="btn btn-default btn-block">1</button>
                                </div>
                                <div class="col">
                                    <button type="button" class="btn btn-default btn-block">2</button>
                                </div>
                                <div class="col">
                                    <button type="button" class="btn btn-default btn-block">3</button>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <button type="button" class="btn btn-default btn-block">4</button>
                                </div>
                                <div class="col">
                                    <button type="button" class="btn btn-default btn-block">5</button>
                                </div>
                                <div class="col">
                                    <button type="button" class="btn btn-default btn-block">6</button>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <button type="button" class="btn btn-default btn-block">7</button>
                                </div>
                                <div class="col">
                                    <button type="button" class="btn btn-default btn-block">8</button>
                                </div>
                                <div class="col">
                                    <button type="button" class="btn btn-default btn-block">9</button>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <button type="button" class="btn btn-default btn-block">Clear</button>
                                </div>
                                <div class="col">
                                    <button type="button" class="btn btn-default btn-block">0</button>
                                </div>
                                <div class="col">
                                    <button type="button" class="btn btn-default btn-block">Delete</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <br><br><br>

    <div class="container">
        <table class="table" style="table-layout: fixed; width: 100%;">
            <thead class="table-dark">
            <tr>
                <th>Date</th>
                <th>Amount</th>
                <th>Status</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for invoice in invoices %}
                <tr>
                    <td>{{ invoice.createdAt|date('d.m.Y H:i') }}</td>
                    <td>{{ invoice.niceAmount }}</td>
                    <td>{% if loop.first %}Waiting{% else %}{{ invoice.niceState }}{% endif %}</td>
                    <td>
                        <a href="#">{% if loop.first %}Hide{% else %}Show{% endif %}</a>
                        <a href="#">Details</a>
                        <a href="#">{% if loop.first %}{% else %}Refund{% endif %}</a>
                    </td>
                </tr>
                {% if loop.first %}
                    <tr>
                        <td>
                            <img src='{{ qrcode_path(invoice.qrCodeMessage, {'size': 150, 'margin': 0}) }}'
                                 alt='LightningCode'>
                        </td>
                        <td style="word-break: break-all; display: inline-block;">
                            {{ invoice.qrCodeMessage }}
                        </td>
                        <td></td>
                        <td></td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}